Changed yaml files

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -2,19 +2,25 @@
 
 name: Spring Data GitHub Issues
 
-on:
-  issues:
-    types: [opened, edited, reopened]
-  issue_comment:
-    types: [created]
-  pull_request_target:
-    types: [opened, edited, reopened]
+on: [push]
 
 jobs:
   Inbox:
     runs-on: ubuntu-latest
-    if: github.repository_owner == 'spring-projects' && (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.pull_request == null
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/spring-data-redis/spring-data-redis/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+      - run: touch starting_Inbox_CreateorUpdateIssueCard_18
+      - run: rm starting_Inbox_CreateorUpdateIssueCard_18
       - name: Create or Update Issue Card
         uses: peter-evans/create-or-update-project-card@v1.1.2
         with:
@@ -22,10 +28,53 @@ jobs:
           column-name: 'Inbox'
           project-location: 'spring-projects'
           token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'spring-data-redis/.github/workflows/project/Inbox'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
   Pull-Request:
     runs-on: ubuntu-latest
-    if: github.repository_owner == 'spring-projects' && (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.pull_request != null
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/spring-data-redis/spring-data-redis/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+      - run: touch starting_PullRequest_CreateorUpdatePullRequestCard_29
+      - run: rm starting_PullRequest_CreateorUpdatePullRequestCard_29
       - name: Create or Update Pull Request Card
         uses: peter-evans/create-or-update-project-card@v1.1.2
         with:
@@ -34,10 +83,53 @@ jobs:
           project-location: 'spring-projects'
           issue-number: ${{ github.event.pull_request.number }}
           token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'spring-data-redis/.github/workflows/project/PullRequest'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
   Feedback-Provided:
     runs-on: ubuntu-latest
-    if: github.repository_owner == 'spring-projects' && github.event_name == 'issue_comment' && github.event.action == 'created' && github.actor != 'spring-projects-issues' && github.event.pull_request == null && github.event.issue.state == 'open' && contains(toJSON(github.event.issue.labels), 'waiting-for-feedback')
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/spring-data-redis/spring-data-redis/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+      - run: touch starting_FeedbackProvided_UpdateProjectCard_41
+      - run: rm starting_FeedbackProvided_UpdateProjectCard_41
       - name: Update Project Card
         uses: peter-evans/create-or-update-project-card@v1.1.2
         with:
@@ -45,3 +137,34 @@ jobs:
           column-name: 'Feedback provided'
           project-location: 'spring-projects'
           token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'spring-data-redis/.github/workflows/project/FeedbackProvided'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
